import Link from "next/link";
import style1 from '@/styles/app.module.css';
import style2 from '@/styles/list_product.module.css';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import AppHeader from '@/components/app.header';
import AppFooter from '@/components/app.footer';
import Container from 'react-bootstrap/Container';
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          {/* <div id="menu">menu
            <ul>
              <li><Link href={"/"}>Trang chủ</Link></li>
              <li><Link href={"/admin/list_product"}>Xem sản phẩm</Link></li>
              <li><Link href={"/admin/add_product"}>Thêm sản phẩm</Link></li>
            </ul>
          </div> */}
          <AppHeader />
        </header>
        <Container>
          {children}
        </Container>
        <footer>
          <AppFooter />
        </footer>
        <ToastContainer
          position="top-center"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
        />
      </body>
    </html>
  );
}
